import React, { useEffect, useState } from 'react';
import { useParams, useLocation, useOutletContext, Link } from 'react-router-dom';
import { findContentByPath, getAllContentItems, ContentItem } from '@/content/mockData';
import { AlertCircle, FileText } from 'lucide-react';
import SimpleRenderer from '@/components/SimpleRenderer';
import { TocItem } from '@/types';
import { AppContextType } from '@/components/Layout'; // Import the context type
import { extractMarkdownBody } from '@/lib/utils'; // Import the new utility

const ContentPage: React.FC = () => {
  const params = useParams();
  const location = useLocation();
  const [contentItem, setContentItem] = useState<ContentItem | null | undefined>(undefined);
  
  // Use the new context type
  const { setTocItems, setCurrentContentItem, setAllNotesForContext } = useOutletContext<AppContextType>();

  const [allNotesAndTopics, setAllNotesAndTopics] = useState<ContentItem[]>([]);
  const [glossaryTerms, setGlossaryTerms] = useState<ContentItem[]>([]);

  useEffect(() => {
    const allItems = getAllContentItems();
    const notesAndTopics = allItems.filter(item => 
      item.type === 'note' || 
      item.type === 'topic' || 
      item.type === 'log' || 
      item.type === 'dictionary_entry'
    );
    setAllNotesAndTopics(notesAndTopics);
    setAllNotesForContext(notesAndTopics); // Set for context

    const terms = allItems.filter(item => item.type === 'glossary_term');
    setGlossaryTerms(terms);

    const path = params['*'];
    if (path) {
      const item = findContentByPath(path);
      setContentItem(item);
      setCurrentContentItem(item); // Set for context

      // Initialize TOC items based on whether content exists and is not just frontmatter
      if (item) {
        const markdownBody = extractMarkdownBody(item.content);
        if (!markdownBody) { // If content is empty after stripping frontmatter
          setTocItems([]);
        }
        // TOC will be generated by SimpleRenderer if markdownBody is not empty
      } else {
        setTocItems([]);
      }
    } else {
      setContentItem(null); 
      setCurrentContentItem(null); // Set for context
      setTocItems([]);
    }
  }, [params, location.pathname, setTocItems, setCurrentContentItem, setAllNotesForContext]);

  if (contentItem === undefined) {
    return (
      <div className="flex items-center justify-center h-full">
        <p className="text-muted-foreground">Loading content...</p>
      </div>
    );
  }

  if (!contentItem) {
    return (
      <div className="container mx-auto py-8 text-center animate-fade-in">
        <AlertCircle className="h-16 w-16 text-destructive mx-auto mb-4" />
        <h1 className="text-3xl font-bold mb-2">Content Not Found</h1>
        <p className="text-muted-foreground">
          The page or note you were looking for ({params['*']}) could not be found.
        </p>
        <p className="mt-4">
          Please check the URL or navigate using the sidebar.
        </p>
      </div>
    );
  }

  const markdownContentToRender = extractMarkdownBody(contentItem.content);

  if (contentItem.type === 'folder') {
    return (
      <div className="container mx-auto py-8 animate-fade-in">
        <header className="mb-8">
          <h1 className="text-4xl font-bold text-primary mb-2">{contentItem.title}</h1>
          <p className="text-sm text-muted-foreground">
            Type: {contentItem.type} | Path: /content/{contentItem.path}
          </p>
        </header>
        <p className="text-muted-foreground mb-4">This is a category or folder. Select an item from its children in the sidebar, or this folder might have its own content below.</p>
        
        {markdownContentToRender ? (
          <SimpleRenderer 
            content={markdownContentToRender} 
            setTocItems={setTocItems} 
            allNotes={allNotesAndTopics}
            glossaryTerms={glossaryTerms}
          />
        ) : (
          contentItem.children && contentItem.children.length > 0 && (
            <div>
              <h2 className="text-xl font-semibold mb-2 mt-6">Contents:</h2>
              <ul className="list-disc list-inside space-y-1">
                {contentItem.children.map(child => (
                  <li key={child.id}>
                    <Link to={`/content/${child.path}`} className="custom-link">
                      {child.title} ({child.type})
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          )
        )}
        {!markdownContentToRender && (!contentItem.children || contentItem.children.length === 0) && (
          <p className="text-muted-foreground">This folder is currently empty or has no overview content.</p>
        )}
      </div>
    );
  }

  return (
    <article className="container mx-auto py-8 animate-fade-in">
      <header className="mb-8">
        <h1 className="text-4xl font-bold text-primary mb-2">{contentItem.title}</h1>
        <p className="text-sm text-muted-foreground">
          Type: {contentItem.type} | Path: /content/{contentItem.path}
          {contentItem.created && ` | Created: ${new Date(contentItem.created).toLocaleDateString()}`}
          {contentItem.lastUpdated && ` | Updated: ${new Date(contentItem.lastUpdated).toLocaleDateString()}`}
        </p>
        {contentItem.frontmatter?.source && (
          <p className="text-xs text-muted-foreground">Source: {contentItem.frontmatter.source}</p>
        )}
        {contentItem.tags && contentItem.tags.length > 0 && (
          <div className="mt-2 flex flex-wrap gap-2">
            {contentItem.tags.map(tag => (
              <span key={tag} className="text-xs bg-secondary text-secondary-foreground px-2 py-0.5 rounded-full">{tag}</span>
            ))}
          </div>
        )}
      </header>
      
      {markdownContentToRender ? (
        <SimpleRenderer 
          content={markdownContentToRender} 
          setTocItems={setTocItems}
          allNotes={allNotesAndTopics}
          glossaryTerms={glossaryTerms}
        />
      ) : (
        <div className="flex flex-col items-center justify-center text-center text-muted-foreground p-8 border border-dashed rounded-lg">
          <FileText className="h-12 w-12 mb-4" />
          <p>No content available for this item yet.</p>
          <p className="text-sm">This might be a note that is pending content.</p>
        </div>
      )}
    </article>
  );
};

export default ContentPage;
